project_id = "gormmhkyozvbrmqtwjyp"

[functions.check-overdue-tasks]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false

[functions.notify-share]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false